// // generated by unplugin-vue-components
// // We suggest you to commit this file into source control
// // Read more: https://github.com/vuejs/core/pull/3399
// import '@vue/runtime-core'

// export {}

// declare module '@vue/runtime-core' {
//   export interface GlobalComponents {
//     AButton: typeof import('ant-design-vue/es')['Button']
//     ElButton: typeof import('element-plus/es')['ElButton']
//     ElIcon: typeof import('element-plus/es')['ElIcon']
//     ElMenu: typeof import('element-plus/es')['ElMenu']
//     ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
//     ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
//     ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
//     ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
//     ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
//     HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
//     IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
//     IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
//     IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
//     IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
//     IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
//     Menu: typeof import('./src/components/Menu.vue')['default']
//     RouterLink: typeof import('vue-router')['RouterLink']
//     RouterView: typeof import('vue-router')['RouterView']
//     TestOne1: typeof import('./src/components/TestOne1.vue')['default']
//     TestOne2: typeof import('./src/components/TestOne2.vue')['default']
//     TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
//     WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
//   }
// }
